
on:
  push:
    branches: [ "master" ]


jobs:

  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    # Checkout to the repository
    - uses: actions/checkout@v3

     # We need to login so we can later push the image without issues.
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # Builds image
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: anaosnia/express-app:latest
  
  
  publish-huggingface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to huggingface
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: ${{ vars.HF_USERNAME }}
        run: git push --force https://$HF_USER:$HF_TOKEN@huggingface.co/spaces/$HF_USER/express-app master:main 
